#!/bin/bash
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=25
#SBATCH --time=12:00:00
#SBATCH --account=PAS1548
#SBATCH --job-name=itsx
#SBATCH --mail-type=ALL

module load gnu/9.1.0
module load mkl/2019.0.5
module load R/4.0.2

# Pre-setup
clear
set -e -u -o pipefail    # Run bash in "safe mode", basically

# Global variables
CURRENTTIME=$(date +"%I:%M %p")

# Report:
echo -e "\n[$CURRENTTIME] Starting itsx script."

# Setup, indir=ITSx output folder, indir2=location with original fq files, outdir=final directory (starting point for dada2)
indir1="/fs/scratch/PAS1548/22_BrandenITSx"
indir2="/fs/scratch/PAS1548/2022_BrandenRCoverCrops/31*"
outdir="/fs/scratch/PAS1548/22_Brandenfqfinal"

# Create output directory if it doesn't already exist:
mkdir -p $outdir

# Report:
echo "[$CURRENTTIME] Input dir:       $indir1"
echo "[$CURRENTTIME] Output dir:      $outdir"

# Software - making doubly sure this is all loaded:
module load python/3.6-conda5.2                          # Load conda module 
source activate itsx                                      # Activate ITSx environment

# Report
echo -e "[$CURRENTTIME] Looping through input files..."

# Get input files
F1=($(ls -1v $indir1/*.full.fasta))
F2=($(ls -1v $indir2/*.fq))

# F1=($(find $indir1 -type f -name "*.full.fasta" -exec echo '{}' \; | sort -V))
# F2=($(find $indir2 -type f -name "*.fq" -exec echo '{}' \; | sort -V))

for i in "${!F2[@]}" 
do
    # Files setup
    R1=$(basename ${F1[i]}) # Get basename (i.e 3178_sample_MM-10.full.fasta)
    R2=${R1%.full.fasta}    # Get sample name (i.e 3178_sample_MM-10)
    
    IN1=${F1[i]}
    IN2=${F2[i]}
    OUT=$outdir/$R2.fq
    
    # # Report
    echo "[$CURRENTTIME] Processing: \n \t\t $IN1 \t\t$IN1"
    
    # Run ITSx
    Rscript ./fastq-from-ITSx/itsx_fastq_extractor.r \
    -f $IN1 \
    -q $IN2 \
    -o $OUT \
    --threads 8
    # break
done

echo -e "[$CURRENTTIME] Done with itsx script.\n"